// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWGSZLfocUbL6RbYFalRfPwfb1IjLRMrE',
    appId: '1:237556993058:web:19c72b5e13da444ac6ce7b',
    messagingSenderId: '237556993058',
    projectId: 'grownext-a20d4',
    authDomain: 'grownext-a20d4.firebaseapp.com',
    storageBucket: 'grownext-a20d4.firebasestorage.app',
    measurementId: 'G-JQFHPFG0KB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqVpaBKVVtWFt66yPdjfaRlwygHKlfzhU',
    appId: '1:237556993058:android:a68bc1b461da13cbc6ce7b',
    messagingSenderId: '237556993058',
    projectId: 'grownext-a20d4',
    storageBucket: 'grownext-a20d4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDD0WV8DcE3aJDvtjqhzEiOhAO1pi-YCTk',
    appId: '1:237556993058:ios:82dacebfe5d9da33c6ce7b',
    messagingSenderId: '237556993058',
    projectId: 'grownext-a20d4',
    storageBucket: 'grownext-a20d4.firebasestorage.app',
    iosBundleId: 'com.grownext.dev',
  );

}